export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';

export const GET_WORKSPACES = 'GET_WORKSPACES';
export const WORKSPACES_ERROR = 'GET_WORKSPACES_ERROR';
export const WORKSPACES_UNLOADED = 'WORKSPACES_UNLOADED';

export const GET_WORKSPACE_DATA = 'GET_WORKSPACE_DATA';
export const SET_ACTIVE_CHANNEL = 'SET_ACTIVE_CHANNEL';
export const WORKSPACE_ERROR = 'WORKSPACE_ERROR';
export const WORKSPACE_UNLOADED = 'WORKSPACE_UNLOADED';

export const GET_CHANNEL_DATA = 'GET_CHANNEL_DATA';
export const NEW_CHANNEL_MESSAGE = 'NEW_CHANNEL_MESSAGE';
